name: Rodar Pipeline
on: 
  pull_request

jobs:
  build: 
    name: Build Project 
    runs-on: macOS-latest
    steps:
    - name: Configurando Ambiente
      uses: actions/checkout@v1

    - name: Build Simulate
      run: xcodebuild  clean build test -project Momondo/Momondo.xcodeproj -scheme Momondo -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14"